import type { Metadata } from "next";
import "./globals.css";
import AuthContext from "./context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <AuthContext>{children}</AuthContext>
      </body>
    </html>
  );
}
